---
include:
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: chocoflan_dongle
  - board: nice_nano_v2
    shield: chocoflan_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: chocoflan_right nice_view_adapter nice_view
